robot_info:
  robot: !!str talos_legs
  ref_config: !!str half_sitting
  rightFoot: !!str right_sole_link
  leftFoot: !!str left_sole_link
  kickFoot:  !!str right_sole_link
traj_params:
  DT: !!float 0.025
  T: !!int 40
  T_standup: !!int 10
  T_windup: !!int 10
  T_kick: !!int 10
  T_recovery: !!int 10
  T_balance: !!int 10
  ball_radius: 0.11
  target: [0.4, -0.3, 0.51]
  kickFootWindupPos: [-0.3, -0.3, 0.2]
  kickFootLandingPos: [0.5, 0.0, 0.0]
debug_info:
  display_step: !!bool false
  plot: !!bool false
  experiment_name: !!str jump
  save_dir_path: !!str soccer_results

jumping_params:
  height: 0.1
  step: [0.3, 0.0, 0.0]
  landingLocation: [0.5, 0.2, 0.0]
  targetLocation: [0.6, -0.4, 0.0]
  stepFoot: left_sole_link
  groundKnots: 5
  flyingKnots: 5
  kickKnots: 1
  recoveryKnots: 2
  jumpKnots: 10
  timeStep: 0.02

kick_params:
  targetLocation: [0.6, -0.4, 0.0]
  kickKnots: 10
  recoveryKnots: 10
